/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 katarina.gltf
Author: Kari (https://sketchfab.com/keetos349)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/katarina-league-of-legends-1b21953e3d0b44dc9aa9e226d86fe2ab
Title: Katarina - League Of Legends
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'

const Kata = (props) => {
  const { nodes, materials } = useGLTF('/katarina.gltf')
  const [dataRot, setDataRot] = useState(0);

  useEffect(() => {
    setTimeout(() => {
      if (dataRot < 6.2) {
        let newData = dataRot + 0.01;
        setDataRot(newData);
      } else {
        setDataRot(0);
      }
    }, 10);    
  }, [dataRot]);

  return (
    <group {...props} dispose={null} position={[0, -2.5, 0]} >
      <mesh geometry={nodes.Object_2.geometry} material={materials.DefaultMaterial} rotation={[-Math.PI / 2, 0, dataRot]} scale={0.08} />
    </group>
  )
}

useGLTF.preload('/katarina.gltf')
export default Kata;
