/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 lux.gltf
Author: jimmy8787 (https://sketchfab.com/jimmy8787878787)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lux-light-e1e3acf476fd402b90febe08a8ddab44
Title: Lux Light
*/

import React, { useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';

const Modelo = (props) => {
  const { nodes, materials } = useGLTF('/lux.gltf')

  const [dataRot, setDataRot] = useState(0);

  useEffect(() => {
    setTimeout(() => {
      if (dataRot < 6.2) {
        let newData = dataRot + 0.01;
        setDataRot(newData);
      } else {
        setDataRot(0);
      }
    }, 10);    
  }, [dataRot]);

  return (
    <group {...props} dispose={null}>
      <group position={[0, -2, 0]} rotation={[-1.5, 0, dataRot]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Light_Body.geometry} material={materials.Light_Body} />
            <mesh geometry={nodes.Light_Collar.geometry} material={materials.Light_Collar} />
            <mesh geometry={nodes.Light_Staff.geometry} material={materials.Light_Staff} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lux.gltf')
export default Modelo;
