/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 worldcup.gltf
Author: waimus (https://sketchfab.com/waimus)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/world-cup-trophy-c4ae2dd470194a81b856ad84620d8beb
Title: World Cup Trophy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Model = (props) => {
  const { nodes, materials } = useGLTF('/worldcup.gltf')
  return (
    <group {...props} dispose={null} position={[0, -2, 0]} >
      <mesh geometry={nodes.wctrophy_globe_low_globe_0.geometry} material={materials.globe} rotation={[-Math.PI / 2, 0, 0]} scale={0.75} />
      <mesh geometry={nodes.wctrophy_body_low_body_0.geometry} material={materials.body} rotation={[-Math.PI / 2, 0, 0]} scale={0.75} />
    </group>
  )
}

useGLTF.preload('/worldcup.gltf')
export default Model;
